### PR TITLE
Added unit tests and a "service" for one-hot encoding

### PR DESCRIPTION
**Pull request by dirrelito**
## Content

Stuff added:
+ .editorconfig to get ending line breaks
+ Many unit tests

Stuff changed:
+ Major refactorizations to file structure
+ Some changes to library structure (moving som functions into sub-modules)
+ The oneHotEncode/-decode is moved to a sub-module and logic is encapsulated in a object. Factory pattern is used to get a coding service from token sets or training data.

## Rationale:
I want to create helper objects for padding and for hot-encoding and for network use, so that all such logic is contained in this library. That way, I could move more of that logic away from the sprakpolisen-ml-use service, and make it easier to inject new ML models into it.

### CODE REVIEW

**Comment by dirrelito** [comment]
I have comptemplated a bit and think this is in the right direction. Accepting the updates to have a good bases to build from further.

To make sure I work in the direction of #5 and #6 , I will make some more changes before merging the PR.

**Comment by dirrelito** [comment]
This now fixes issues #3 and #5  and #6 

Please accept @marcusahl  ^_^

**Comment by dirrelito** [comment]
I am **so** eager to continue, so I'll merge this in and hack away!

**Comment by marcusahl** [comment]
:+1

2017-06-14 15:00 GMT-04:00 Ludvig <notifications@github.com>:

**Pull request merged**
